<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Wayfinder/Wayfinder.csproj" />
    <ProjectReference Include="../Wayfinder.Engine/Wayfinder.Engine.csproj" />
    <ProjectReference Include="../Wayfinder.Editor.Http/Wayfinder.Editor.Http.csproj" />
    <ProjectReference Include="../Wayfinder.Engine.Api/Wayfinder.Engine.Api.csproj" />
    <ProjectReference Include="../Wayfinder.Engine.Http/Wayfinder.Engine.Http.csproj" />
    <ProjectReference Include="../Wayfinder.Engine.Journey/Wayfinder.Engine.Journey.csproj" />
    <ProjectReference Include="../Wayfinder.Engine.Mcp/Wayfinder.Engine.Mcp.csproj" />
    <ProjectReference Include="../Wayfinder.Engine.Worklist/Wayfinder.Engine.Worklist.csproj" />
    <ProjectReference Include="../Wayfinder.Rendering.GovUk/Wayfinder.Rendering.GovUk.csproj" />
  </ItemGroup>

</Project>
