using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace Wayfinder.TypeGen;

/// <summary>
/// Walks the C# types a <see cref="JsonSerializerOptions"/> can (de)serialize and writes the
/// matching TypeScript declarations. The serializer's own metadata is the source — property
/// names, polymorphic discriminators, enum representation — so the TypeScript says exactly what
/// the wire says. A property is optional when its C# type is nullable.
/// </summary>
public sealed class TypeScriptEmitter(JsonSerializerOptions options)
{
    private readonly NullabilityInfoContext _nullability = new();
    private readonly SortedDictionary<string, string> _declarations = new(StringComparer.Ordinal);
    private readonly Dictionary<string, Type> _namedTypes = new(StringComparer.Ordinal);
    private readonly Queue<Type> _pending = new();

    public string Emit(IEnumerable<Type> roots)
    {
        foreach (var root in roots)
        {
            Reference(root);
        }

        while (_pending.TryDequeue(out var type))
        {
            Declare(type);
        }

        var output = new StringBuilder();
        output.Append("// <auto-generated>\n");
        output.Append("// Generated from the C# model by Wayfinder.TypeGen. Do not edit by hand:\n");
        output.Append("//   dotnet run --project Wayfinder.TypeGen -- write <this file>\n");
        output.Append("// </auto-generated>\n\n");
        output.Append(string.Join("\n", _declarations.Values));
        return output.ToString();
    }

    /// <summary>The TypeScript expression for a type, queuing a declaration for any named type it needs.</summary>
    private string Reference(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;

        if (Primitive(type) is { } primitive)
        {
            return primitive;
        }

        var info = options.GetTypeInfo(type);
        if (info.Kind == JsonTypeInfoKind.Dictionary)
        {
            return $"Record<string, {Reference(info.ElementType!)}>";
        }

        if (info.Kind == JsonTypeInfoKind.Enumerable)
        {
            var element = Reference(info.ElementType!);
            return element.Contains(' ') ? $"({element})[]" : $"{element}[]";
        }

        return Name(type);
    }

    private static string? Primitive(Type type)
    {
        if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime)
            || type == typeof(DateTimeOffset) || type == typeof(TimeSpan) || type == typeof(Uri))
        {
            return "string";
        }

        if (type == typeof(bool))
        {
            return "boolean";
        }

        if (type == typeof(JsonObject))
        {
            return "Record<string, unknown>";
        }

        if (type == typeof(JsonArray))
        {
            return "unknown[]";
        }

        if (type == typeof(object) || type == typeof(JsonNode) || type == typeof(JsonElement))
        {
            return "unknown";
        }

        return type.IsPrimitive || type == typeof(decimal) ? "number" : null;
    }

    private string Name(Type type)
    {
        if (_namedTypes.TryGetValue(type.Name, out var existing))
        {
            return existing == type
                ? type.Name
                : throw new InvalidOperationException($"Two C# types are both named {type.Name}: {existing.FullName} and {type.FullName}.");
        }

        _namedTypes[type.Name] = type;
        _pending.Enqueue(type);
        return type.Name;
    }

    private void Declare(Type type)
    {
        var info = options.GetTypeInfo(type);
        _declarations[type.Name] = type.IsEnum
            ? DeclareEnum(type)
            : info.PolymorphismOptions is { } polymorphism
                ? DeclarePolymorphic(type, polymorphism)
                : DeclareInterface(type.Name, info, discriminator: null);
    }

    private static string DeclareEnum(Type type)
    {
        if (type.GetCustomAttribute<JsonConverterAttribute>()?.ConverterType?.Name.Contains("StringEnum", StringComparison.Ordinal) != true)
        {
            throw new InvalidOperationException($"{type.Name} is not serialized as a string; teach the emitter its representation.");
        }

        var values = string.Join(", ", Enum.GetNames(type).Select(name => $"'{name}'"));
        var constant = char.ToLowerInvariant(type.Name[0]) + type.Name[1..] + "Values";
        return $"export const {constant} = [{values}] as const;\nexport type {type.Name} = (typeof {constant})[number];\n";
    }

    private string DeclarePolymorphic(Type baseType, JsonPolymorphismOptions polymorphism)
    {
        var members = new List<string>();
        var declarations = new StringBuilder();
        foreach (var derived in polymorphism.DerivedTypes)
        {
            var discriminator = (polymorphism.TypeDiscriminatorPropertyName, derived.TypeDiscriminator);
            declarations.Append(DeclareInterface(derived.DerivedType.Name, options.GetTypeInfo(derived.DerivedType), discriminator!));
            members.Add(derived.DerivedType.Name);
        }

        declarations.Append(CultureInfo.InvariantCulture, $"export type {baseType.Name} =\n  | {string.Join("\n  | ", members)};\n");
        return declarations.ToString();
    }

    private string DeclareInterface(string name, JsonTypeInfo info, (string Property, object Value)? discriminator)
    {
        var body = new StringBuilder();
        if (discriminator is var (property, value))
        {
            body.Append(CultureInfo.InvariantCulture, $"  {property}: {Literal(value)};\n");
        }

        foreach (var member in info.Properties)
        {
            var optional = member.IsRequired ? "" : IsNullable(member) ? "?" : "";
            var tsType = ConverterOverride(member) ?? Reference(member.PropertyType);
            body.Append(CultureInfo.InvariantCulture, $"  {Key(member.Name)}{optional}: {tsType};\n");
        }

        return $"export interface {name} {{\n{body}}}\n";
    }

    /// <summary>
    /// A property-level <c>[JsonConverter]</c> can change the wire shape. Converters over a string
    /// (or a <see cref="Type"/>, written as its name) are plain strings on the wire; any other has to be taught
    /// here, because guessing would let the TypeScript drift from the wire.
    /// </summary>
    private static string? ConverterOverride(JsonPropertyInfo member)
    {
        var converter = member.AttributeProvider?.GetCustomAttributes(typeof(JsonConverterAttribute), inherit: true)
            .OfType<JsonConverterAttribute>().FirstOrDefault()?.ConverterType;
        if (converter is null)
        {
            return null;
        }

        for (var type = converter; type is not null; type = type.BaseType)
        {
            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(JsonConverter<>)
                && type.GetGenericArguments()[0] is var written && (written == typeof(string) || written == typeof(Type)))
            {
                return "string";
            }
        }

        throw new InvalidOperationException(
            $"{member.Name} uses {converter.Name}; teach TypeScriptEmitter.ConverterOverride the shape it writes.");
    }

    private bool IsNullable(JsonPropertyInfo member)
    {
        if (Nullable.GetUnderlyingType(member.PropertyType) is not null)
        {
            return true;
        }

        return member.AttributeProvider is PropertyInfo property
            && _nullability.Create(property).ReadState == NullabilityState.Nullable;
    }

    private static string Literal(object value) => value is string text ? $"'{text}'" : value.ToString()!;

    private static string Key(string name) =>
        name.All(c => char.IsLetterOrDigit(c) || c == '_') && !char.IsDigit(name[0]) ? name : $"'{name}'";
}
